# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Use R language
language: r
# Test for multiple R-versions, one from bioconductor
r:
  - oldrel
  - release
  - devel
  - bioc-devel

# Test for multiple operating systems
os:
  - linux
  - osx
  
cache: packages
