on:
  schedule:
    - cron:  '00 23 * * *'

name: Refresh downloads

jobs:
  render:
    name: render README.md
    runs-on: windows-latest
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: development
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      # install packages needed
      - name: Install required packages and render README
        run: |
          install.packages(c("remotes", "rmarkdown", "cranlogs", "lubridate", "plyr", "ggplot2", "scales", "maptools", "installr", "data.table", "svglite"))
          rmarkdown::render("README.Rmd")
        shell: Rscript {0}

      - name: Commit updated images and dataset to development
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add man/figures/readme/downloads/downloads.svg man/figures/readme/worldmap/worldmap.svg man/figures/readme/worldmap/downloads.csv 
          git commit -m "Update downloads" || echo "No changes to commit"
          git push origin development || echo "No changes to commit"