on:
  schedule:
    - cron:  '00 02 * * *'

name: Update package statistics

jobs:
  update:
    name: Update package statistics
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      
      # Step 1: Checks-out the jfa repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      # Step 2: Get the current date for the PR name
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Step 3: Install required packages
      - name:  Install required packages
        run: |
          install.packages(c("cranlogs", "lubridate", "plyr", "ggplot2", "scales", "maptools", "installr", "data.table", "svglite"))
        shell: Rscript {0}

      # Step 4: Render relevant data and figures
      - name: Render relevant data and figures
        run: |
          source(".github/workflows/render-figures.R")
        shell: Rscript {0}

      # Step 5: Create a pull request with the updated data and figures to development
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Package statistics update for ${{ steps.date.outputs.date }}" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}